#!/usr/bin/env python2
"""Testing arm movement. 
"""

import sys
import copy 
import rospy 
import moveit_commander 
import moveit_msgs.msg
import geometry_msgs.msg

moveit_commander.roscpp_initializer(sys.argv)
rospy.init_node('testing_movement', anonymous=True)

robot = moveit_commander.RobotCommander()
